name: enough_platform_widgets
description: Useful platform aware widgets to develop a Flutter app with either Cupertino and Material design.
version: 1.1.1
homepage: https://github.com/Enough-Software/enough_platform_widgets
topics: 
 - cupertino
 - material
 - widgets

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  cupertino_stepper: ^0.2.1
  cupertino_progress_bar: ^0.2.0
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
